import type { Metadata } from "next";
import {
  DM_Sans,
  Source_Code_Pro,
  Poppins,
  Port_Lligat_Sans,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

// — DM Sans —
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // solo los pesos necesarios
  variable: "--font-dm-sans", // nombre de la CSS var que quieres exponer
});

// — Source Code Pro —
const sourceCode = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-source-code",
});

// — Poppins —
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

// — Port Lligat Sans —
const portLligatSans = Port_Lligat_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-port-lligat-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${sourceCode.variable} ${poppins.variable} ${portLligatSans.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
